// One-time setup: generate a dedicated bot wallet and write .env for you.
//   npm run setup
//
// This creates a fresh burner wallet the bot controls. You fund it by sending
// SOL to the printed address from Phantom. Nothing else to edit.
import { Keypair } from '@solana/web3.js';
import bs58 from 'bs58';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const dir = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(dir, '..');
const envPath = path.join(root, '.env');

if (fs.existsSync(envPath)) {
  console.log('⚠  .env already exists — not overwriting it.');
  console.log('   Delete it first if you want a fresh wallet, then re-run setup.');
  process.exit(0);
}

const kp = Keypair.generate();
const secret = bs58.encode(kp.secretKey);
const address = kp.publicKey.toBase58();

const env = `# Generated by npm run setup on ${new Date().toISOString()}
CLAUDE_PROXY_URL=http://localhost:8787
CLAUDE_PROXY_PORT=8787
CLAUDE_MODEL=claude-opus-4-8

# The bot's own wallet. Fund it by sending SOL to the address below from Phantom.
SOLANA_PRIVATE_KEY=${secret}
SOLANA_RPC_URL=https://api.mainnet-beta.solana.com

EXECUTION_MODE=local
PUMPPORTAL_API_KEY=
PUMPPORTAL_WS_API_KEY=

BUY_AMOUNT_SOL=0.05
MAX_POSITION_SOL=0.10
MAX_OPEN_POSITIONS=3
MAX_DAILY_SPEND_SOL=0.50
SLIPPAGE_PERCENT=10
PRIORITY_FEE_SOL=0.00005
MIN_CONFIDENCE=0.65
TAKE_PROFIT_PCT=0.5
STOP_LOSS_PCT=0.3

# First run is dry (no real trades). Use "npm run start:live" to trade for real.
DRY_RUN=true
I_UNDERSTAND_LIVE_TRADING=false
KILL_SWITCH=false
`;

fs.writeFileSync(envPath, env);

console.log('\n✅ Setup complete. Your bot wallet has been created.\n');
console.log('   ┌─────────────────────────────────────────────────────────────');
console.log('   │  FUND THIS ADDRESS FROM PHANTOM:');
console.log(`   │  ${address}`);
console.log('   └─────────────────────────────────────────────────────────────\n');
console.log('   1) Open Phantom → Send → paste that address → send some SOL');
console.log('      (start small — e.g. 0.3 SOL. Treat it as fully at-risk.)');
console.log('   2) Check it arrived:   npm run balance');
console.log('   3) Watch it think:     npm start        (dry run, no real trades)');
console.log('   4) Trade for real:     npm run start:live\n');
console.log('   Your key is saved in .env (never commit or share that file).');
console.log('   To withdraw later, send SOL from this wallet back to Phantom.\n');
